[workspace]
resolver = "3"
members = ["glacier", "glacier-core", "glacier-crypto"]

[workspace.package]
version = "1.2.0"
edition = "2024"
description = "Glacier is a backup service for preserving data from the software I use every day."
license = "MIT"
repository = "https://git.lab.itsnova.sh/nova/glacier"

[workspace.metadata.release]
shared-version = true
dependent-version = "upgrade"
publish = false
push = false
verify = true
tag = true
tag-prefix = "v"
tag-name = "v{{version}}"
tag-message = "Release v{{version}}"
pre-release-commit-message = "chore(release): bump version to v{{version}}"
consolidate-commits = true

[workspace.dependencies]
anyhow = "1.0.103"
chrono = "0.4.45"
glacier-core = { version = "1.2.0", path = "glacier-core" }
glacier-crypto = { version = "1.2.0", path = "glacier-crypto" }
tempfile = "3.27.0"
tokio = { version = "1.52.3", features = ["macros", "rt-multi-thread"] }
