[package]
name = "coolify-backups"
version = "0.1.0"
edition = "2024"
description = "A small script to backup the data in some of my services hosted with Coolify."
license = "MIT"
repository = "https://git.lab.itsnova.sh/novaotp/coolify-backups"
publish = ["forgejo"]

[dependencies]
anyhow = "1.0.103"
async-trait = "0.1.89"
aws-config = { version = "1.9.0", features = ["behavior-version-latest"] }
aws-sdk-s3 = "1.138.1"
bytes = "1.12.1"
chrono = "0.4.45"
config = "0.15.25"
dotenvy = "0.15.7"
reqwest = { version = "0.13.4", features = ["json", "query"] }
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.150"
tokio = { version = "1.52.3", features = ["macros", "rt-multi-thread"] }
