[package]
name = "coolify-backups"
version = "0.1.0"
edition = "2024"
description = "A small script to backup the data in some of my services hosted with Coolify."
license = "MIT"
repository = "https://git.lab.itsnova.sh/novaotp/coolify-backups"
publish = ["forgejo"]

[dependencies]
anyhow = "1.0.103"
async-trait = "0.1.89"
aws-config = { version = "1.9.0", features = ["behavior-version-latest"] }
aws-sdk-s3 = "1.138.1"
chrono = "0.4.45"
config = "0.15.25"
dotenvy = "0.15.7"
flate2 = "1.1.9"
futures = "0.3.33"
futures-util = "0.3.33"
quick-xml = { version = "0.41.0", features = ["serialize"] }
reqwest = { version = "0.13.4", features = ["json", "query", "stream"] }
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.150"
tar = "0.4.46"
tempfile = "3.27.0"
tokio = { version = "1.52.3", features = ["macros", "rt-multi-thread"] }
