[package]
name = "glacier"
description = "CLI for Glacier."
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[package.metadata.release]
pre-release-hook = [
    "sh",
    "-c",
    "cd .. && git cliff --unreleased --tag v{{version}} --prepend CHANGELOG.md",
]

[dependencies]
anyhow.workspace = true
chrono.workspace = true
clap = { version = "4.6.4", features = ["cargo", "derive", "env"] }
dotenvy = "0.15.7"
futures = "0.3.33"
glacier-core.workspace = true
glacier-crypto.workspace = true
self_update = "0.44.0"
strum = { version = "0.28.0", features = ["derive"] }
tokio.workspace = true
